services:
    
  nifi:
    image: apache/nifi:1.27.0
    container_name: nifi
    restart: always
    ports:
      - 8443:8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes:
      - ./data:/tmp/data
      # - ./nifi-config:/opt/nifi/nifi-current/conf 
    user: "0:0"
    networks:
      - app-network
    # depends_on:
    #   - mongo
    
  zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017 
    networks:
      - app-network   
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - app-network

  streamlit:
    image: python:3.9-slim
    container_name: streamlit_app
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && streamlit run mapa2.py" 
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - app-network
    depends_on:
      - mongo


networks:
  app-network:
    driver: bridge


volumes:
  data:
  nifi_data:
  mongo_data:
    driver: local
