services:

  streamlit:
    image: python:3.12.6
    container_name: streamlit_app
    volumes:
      - ./:/app
      - ./alquileres_distritos.json:/app/alquileres_distritos.json
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && streamlit run mapa2.py"
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_URI=postgresql://admin:admin@postgres:5432/my_database
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      POSTGRES_DB: DISTRITOS
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
   
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.16
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SERVER: "postgres_container"
      PGADMIN_SERVER_HOST: "postgres"
      PGADMIN_SERVER_PORT: "5432"
      PGADMIN_SERVER_USER: "postgres"
      PGADMIN_SERVER_PASSWORD: "Welcome01"  
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local