services:

  streamlit:
    image: python:3.9-slim
    container_name: streamlit_app
    volumes:
      - ./:/app
      - ./alquileres_distritos.json:/app/alquileres_distritos.json
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && streamlit run mapa2.py" 
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_URI=postgresql://admin:admin@postgres:5432/my_database
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  